# Current Version: 1.0.6

name: Build & Release hezhijie0327/E5Renew

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 */6 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Setup Python Environment
              uses: actions/setup-python@v4.3.0
              with:
                check-latest: true
                python-version: '3.10'
            - name: Step 3 - Install requests
              run: |
                  sudo pip install requests
            - name: Step 4 - Build E5Renew
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/E5Renew/source/E5Renew.py" | sed "s/config\_client\_id/${{ secrets.config_client_id }}/g;s/config\_client\_secret/${{ secrets.config_client_secret }}/g" > "./E5Renew.py"
                  sudo python "./E5Renew.py"
                  sudo rm -rf "./E5Renew.py"
            - name: Step 5 - Release E5Renew
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/Toolkit/main/Git.sh" > "/tmp/Git.sh"
                  sudo bash "/tmp/Git.sh" -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "E5Renew" -i "Generated by GitHub Actions" -m "push"
